Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteNoiBoCongTy.Data;
using WebsiteNoiBoCongTy.Models;

namespace WebsiteNoiBoCongTy.Controllers
{
    public class AccountsController : Controller
    {
        private readonly WebsiteNoiBoCongTyContext _context;

        public AccountsController(WebsiteNoiBoCongTyContext context)
        {
            _context = context;
        }

        // GET: Accounts/Details/5
        public async Task<IActionResult> Details()
        {
            String id = HttpContext.Session.GetString("AccountId");
            if (id == null || _context.Account == null)
            {
                return NotFound();
            }

            var account = await _context.Account
                .Include(a => a.Department)
                .FirstOrDefaultAsync(m => m.AccountId.ToString() == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // GET: Accounts/Edit/5
        public async Task<IActionResult> Edit()
        {
            String id = HttpContext.Session.GetString("AccountId");
            if (id == null || _context.Account == null)
            {
                return NotFound();
            }

            var account = await _context.Account.FirstOrDefaultAsync(
                a => a.AccountId.ToString() == id);
            if (account == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "Name", account.DepartmentId);
            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("AccountId,Username,Fullname,Password,Gender, PhotoURL,Birthday,Position,PhoneNumber,DepartmentId")] Account account)
        {
            String id = HttpContext.Session.GetString("AccountId");
            if (id != account.AccountId.ToString())
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Set<Department>(), "DepartmentId", "Name", account.DepartmentId);
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(account);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountExists(account.AccountId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View(account);
            }
            return View(account);
        }



        private bool AccountExists(int id)
        {
          return (_context.Account?.Any(e => e.AccountId == id)).GetValueOrDefault();
        }

        //======================LOGIN=======================
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            var account = await _context.Account.FirstOrDefaultAsync(c => c.Username == username && c.Password == password);
            if (account == null)
            {
                return View();
            }
            HttpContext.Session.SetString("AccountId", account.AccountId.ToString());
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteNoiBoCongTy.Data;
using WebsiteNoiBoCongTy.Models;

namespace WebsiteNoiBoCongTy.Controllers
{
    public class MeetingsController : Controller
    {
        private readonly WebsiteNoiBoCongTyContext _context;

        public MeetingsController(WebsiteNoiBoCongTyContext context)
        {
            _context = context;
        }

        // GET: Meetings
        public async Task<IActionResult> Index()
        {
            String? id = HttpContext.Session.GetString("AccountId");
            var account = await _context.Account.FirstOrDefaultAsync(acc => acc.AccountId.ToString() == id);

            var websiteNoiBoCongTyContext = _context.Meeting
                .Include(m => m.Department)
                .Include(m => m.Room)
                .Where(m=>m.DepartmentId == account.DepartmentId);
            return View(await websiteNoiBoCongTyContext.ToListAsync());
        }

        // GET: Meetings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Meeting == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meeting
                .Include(m => m.Department)
                .Include(m => m.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }
    }
}

Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteNoiBoCongTy.Data;
using WebsiteNoiBoCongTy.Models;

namespace WebsiteNoiBoCongTy.Controllers
{
    public class NewsController : Controller
    {
        private readonly WebsiteNoiBoCongTyContext _context;

        public NewsController(WebsiteNoiBoCongTyContext context)
        {
            _context = context;
        }

        // GET: News
        public async Task<IActionResult> Index()
        {
            var websiteNoiBoCongTyContext = _context.News.Include(n => n.Author);
            return View(await websiteNoiBoCongTyContext.ToListAsync());
        }

        // GET: News/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.News == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .Include(n => n.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }
    }
}

Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteNoiBoCongTy.Data;
using WebsiteNoiBoCongTy.Models;

namespace WebsiteNoiBoCongTy.Controllers
{
    public class NotificationsController : Controller
    {
        private readonly WebsiteNoiBoCongTyContext _context;

        public NotificationsController(WebsiteNoiBoCongTyContext context)
        {
            _context = context;
        }

        // GET: Notifications
        public async Task<IActionResult> Index()
        {
            String id = HttpContext.Session.GetString("AccountId");
            var websiteNoiBoCongTyContext = _context.Notification.Include(n => n.Account).Where(n => n.AccountId.ToString() == id);
            return View(await websiteNoiBoCongTyContext.ToListAsync());
        }

        // GET: Notifications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Notification == null)
            {
                return NotFound();
            }

            var notification = await _context.Notification
                .Include(n => n.Account)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notification == null)
            {
                return NotFound();
            }

            return View(notification);
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebsiteNoiBoCongTy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebsiteNoiBoCongTy.styles.css" asp-append-version="true" />
    <link href="~/css/styles.min.css" rel="stylesheet" />
    <style>
        .navbar-nav .nav-link {
            font-weight: bold;
            font-size: 1.1rem;
        }
        .navbar-nav .nav-link:hover {
            color: blue !important; 
        }
        .navbar-nav .nav-item {
            margin-left: 15px; 
        }
        .navbar-nav .nav-item:last-child {
            margin-right: 20px; 
        }
        .navbar-nav .logout-link {
            background-color: #629ed2; 
            padding: 7px 50px; 
            border-radius: 10px; 
        }
        .navbar-brand img {
            height: 50px; 
            border-radius: 5px; 
            margin-left: 10px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/TechBits_navi.png" alt="Logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageNews" asp-action="Index">Bảng tin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageMeetings" asp-action="Index">Lịch họp</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageNotifications" asp-action="Index">Thông báo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageAccounts" asp-action="Index">Tài khoản</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageDepartments" asp-action="Index">Phòng ban</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageRooms" asp-action="Index">Phòng họp</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark logout-link" href="http://localhost:5168/AdminLogin/Index">Đăng xuất</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/app.min.js"></script>
    <link href="~/css/styles.min.css" rel="stylesheet" />

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebsiteNoiBoCongTy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebsiteNoiBoCongTy.styles.css" asp-append-version="true" />
    <link href="~/css/styles.min.css" rel="stylesheet" />
    <style>
        .navbar-nav .nav-link {
            font-weight: bold;
            font-size: 1.1rem;
        }
        .navbar-nav .nav-link:hover {
            color: blue !important; 
        }
        .navbar-nav .nav-item {
            margin-left: 15px; 
        }
        .navbar-nav .nav-item:last-child {
            margin-right: 20px; 
        }
        .navbar-nav .logout-link {
            background-color: #629ed2; 
            padding: 7px 50px; 
            border-radius: 10px; 
        }
        .navbar-brand img {
            height: 50px; 
            border-radius: 5px; 
            margin-left: 10px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/TechBits_navi.png" alt="Logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index">Bảng tin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meetings" asp-action="Index">Lịch họp</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">Thông báo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Details">Tài khoản</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark logout-link" asp-area="" asp-controller="Accounts" asp-action="Login">Đăng xuất</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div>
            @await Component.InvokeAsync("Birthdaybar")
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/app.min.js"></script>
    <link href="~/css/styles.min.css" rel="stylesheet" />

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>